### ISSUE TITLE
Неудобство - с прочим доходом

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#11]
был открыт отчет, поставили флаг “Не облагается НДС” у прочей статьи - ничего не поменялось, пришлось переоткрыть отчет

![image](https://user-images.githubusercontent.com/34914654/76680072-ac949400-65f6-11ea-8e04-e93a77a98f4e.png)

**Comment by Oxotka** [comment]
Исправил в закладке - https://github.com/Oxotka/VerificationOfRegulatoryReports/commit/6c6993cffa76c31eeaccd70ed26bac598b339460 , просьба проверить.

**Comment by Oxotka** [comment]
Проверена?

**Comment by mors1eska** [comment]
да, все ок
