### ISSUE TITLE
Не учитывается внереализационная реализация с 4-го квартала 2020

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#12]
![image](https://user-images.githubusercontent.com/34914654/76833933-4e0d2700-683d-11ea-95d3-d1d16ba3a930.png)

http://forum.infostart.ru/forum24/topic179917/message2411151/#message2411151

**Comment by Oxotka** [comment]
Нужны уточнения.
Что нужно сделать то?

**Comment by mors1eska** [comment]
Обновилась форма декларации и скорее всего не ту ячейку анализируем
что бы поправить нужно заполнить декларацию по прибыли за 4й квартал, что бы в ней были внереализационные расходы

по идее они будут легко, с прошлых периодов, даже мучиться не надо

и надо просто проверить в какой ячейке цифра

![image](https://user-images.githubusercontent.com/34914654/76998126-9889c300-6965-11ea-91cd-62b6533e96a1.png)

![image](https://user-images.githubusercontent.com/34914654/76998146-9fb0d100-6965-11ea-9655-b6a1b4d5dbe9.png)

и в анализе сравнений с 91 счетом тоже проверить как там (которое по нажатии на цифре раскрывается)

**Comment by Oxotka** [comment]
Ну у меня данных нет на которых можно проверить. Можешь либо базу, либо посмотреть откуда брать?

**Comment by mors1eska** [comment]
https://drive.google.com/open?id=1XqmWL-BFWwxIKigD14pKNMWItnQOwEeX
