### ISSUE TITLE
Расшифровка показателей разниц

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#15]
Делаем универсально:
Для каждой цифры разниц делаем возможность расшифровки по двойному клику
Берем разницы (постоянные и временные) и тот же запрос, который используем и для отчета
и выводим в разрезе:
- регистратора 
- контрагента
- суммы

![image](https://user-images.githubusercontent.com/34914654/78508693-84c9c380-7791-11ea-9f9d-bec0265b8842.png)

**Comment by Oxotka** [comment]
А что пользователь с этим потом может сделать? Распечатать? Или просто посмотреть и провалиться в документ?
То есть это будет таблица значений или прям табличный документ?

**Comment by mors1eska** [comment]
Основной сценарий - провалиться в документ, но думаю, было бы важно иметь возможность распечататься

**Comment by Oxotka** [comment]
Готово.
Проверь, пожалуйста.
Добавил расшифровку для всех рассчитываемых по учетным данным показателям.

**Comment by mors1eska** [comment]
Не получается расшифровать итоговые периоды
![image](https://user-images.githubusercontent.com/34914654/81140371-c22c9700-8f71-11ea-9cee-6b2ef8bf3f1b.png)

**Comment by Oxotka** [comment]
Исправлено

**Comment by mors1eska** [comment]
чот не понятно расшифровывает
![image](https://user-images.githubusercontent.com/34914654/81374116-2b91de80-9107-11ea-8f0f-e05fa7af77d3.png)

**Comment by mors1eska** [comment]
И давай, наверное, 3-й знак уберем
![image](https://user-images.githubusercontent.com/34914654/81374183-567c3280-9107-11ea-94ad-95c8eebed69a.png)

**Comment by mors1eska** [comment]
И еще, боюсь, сумму не догадаются как посчитать пользователи
(я придумал считать только через выделение и М от калькулятора)

может можно добавить реквизит снизу, который по выделенному будет сумму показывать?

![image](https://user-images.githubusercontent.com/34914654/81374376-c985a900-9107-11ea-8166-1edc01eecb39.png)

Второй вариант -0 разрешить вывод в табличный документ

**Comment by mors1eska** [comment]
> чот не понятно расшифровывает
> ![image](https://user-images.githubusercontent.com/34914654/81374116-2b91de80-9107-11ea-8f0f-e05fa7af77d3.png)

это отменяется
