### ISSUE TITLE
Возврат товаров реализации предыдущего года

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#16]
Нужно добавить в перечень не включаемых внереализационных доходов по 91 счету

"Возврат товаров, реализованных в предыдущем налоговом периоде"

![image](https://user-images.githubusercontent.com/34914654/81285354-12862080-9068-11ea-98f3-e502d3782b3a.png)

Обоснование
http://forum.infostart.ru/forum24/topic179917/message2426629/#message2426629

**Comment by mors1eska** [comment]
@Oxotka понял о чем я?

**Comment by Oxotka** [comment]
> @Oxotka понял о чем я?

Нет, не понятно, что нужно сделать.

**Comment by mors1eska** [comment]
> Нет, не понятно, что нужно сделать.

у нас есть перечень прочих доходов, которые по умолчанию исключаются из сравнения (в которых галка стоит исключить или как так), вот надо просто еще один добавить туда

**Comment by Oxotka** [comment]
Не понял что туда нужно добавить?
Вид прочих доходов и расходов? Какой?

**Comment by mors1eska** [comment]
я ж выше написал =)

"Возврат товаров, реализованных в налоговом периоде"

![image](https://user-images.githubusercontent.com/34914654/81293389-f1c4c780-9075-11ea-9b07-c42ab9615214.png)

**Comment by Oxotka** [comment]
Добавил предопределенный элемент "ВозвратТоваровПрошлыхЛет"
В твоей базе его почему-то нет.
