### ISSUE TITLE
Исключить декларации по обособленным подразделениям из анализа

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#18]
Если организация сдает прибыль по обособкам, то там получается много отчетов, в которых пустой 02 лист.
Надо анализировать декларацию только по головной организации.

![image](https://user-images.githubusercontent.com/34914654/87318134-978e2a00-c530-11ea-9c90-b41cb5439bd7.png)

Как это сделать?

Нужно узнать код налоговой у орагнизации

![image](https://user-images.githubusercontent.com/34914654/87318150-9fe66500-c530-11ea-8fea-49368a431265.png)

И в запросе фильтровать по этому коду

![image](https://user-images.githubusercontent.com/34914654/87318173-a8d73680-c530-11ea-9eef-b92cd263ab17.png)

**Comment by Oxotka** [comment]
Что по этой задаче? Удалось проверить?

**Comment by mors1eska** [comment]
да, отписался чувак, все ок
буду готовить релиз
