### ISSUE TITLE
Ошибка Прочих доходов/расходов

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#19]
В релизе конфигурации Бухгалтерия предприятия, редакция 3.0 (3.0.83.25) обнаружена ошибка (и наблюдается по сегодняшний день) при работе с расширением "БП:Анализ расхождений выручки НДС и Налога на прибыль" в сервисе 1С:ФРЕШ.

При записи нового элемента в справочнике "Прочие доходы и расходы" возникает ошибка:

"Работа с таблицей невозможна. Структура таблицы несовместима с текущими расширениями конфигурации".

**Comment by mors1eska** [comment]
У меня на фреше не воспроизвелось

**Comment by Oxotka** [comment]
Закрываем?
