### ISSUE TITLE
Если поставить флаг "Не облагается НДС" в статье прочего дохода, то надо переоткрывать отчет

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#21]
Если ставим флаг в прочем доходе "не облагается НДС", то в отчет такая строка в разницы не попадет до тех пор пока в отчет не перезайдешь, можно это поправить?

**Comment by Oxotka** [comment]
Покажи воспроизведение. Потому что там все для этого есть, см. вложение.
[ЗаписьПрочихДоходовИРасходов.mp4.zip](https://github.com/Oxotka/VerificationOfRegulatoryReports/files/5683720/mp4.zip)

**Comment by mors1eska** [comment]
приложил свою запись
https://recordit.co/5aQeOTevSN

**Comment by Oxotka** [comment]
Ааа, я понял чего ты хочешь.
Ты хочешь отказаться от настроек совсем. Чтобы мы туда вообще не смотрели, а всегда брали по этим флажкам.

Иначе нельзя что-то дописывать в настройки без ведома пользователя.

**Comment by Oxotka** [comment]
Уверен, что именно так нужно будет делать?

**Comment by mors1eska** [comment]
Ну, наверное, так логичнее будет
т.к. понять, что тебе нужно что-то поставить в исключения можно только по ОСВ по 91 счету
переживаю только за "обратную совместимость", может ли у нас быть такое что элементе прочих доходов галка не стоит, а в списке исключений доход есть? (я имею в виду технически).

Ну и если уходить от настройки в отчете, то надо менять действие кнопки, мое предложение - настройку убрать, а открывать открывать ОСВ по 91 счету при нажатии в отчете

![Uploading image.png…]()

**Comment by Oxotka** [comment]
Если мы добавляем в настройки какой-то элемент прочих доходов и расходов, то у него устанавливается этот флаг.
Давай сделаем так:
1. Я буду добавлять в настройки даже если не открыта настройка
2. Из настроек сделаем отдельной кнопкой переход к ОСВ по 91 счету

**Comment by Oxotka** [comment]
Нужна проверка

**Comment by mors1eska** [comment]
а где кнопка - переход к ОСВ? не увидел
![image](https://user-images.githubusercontent.com/34914654/103455474-94fdd780-4cfe-11eb-9d34-219ebdbe08f3.png)

**Comment by mors1eska** [comment]
И изменения галки не повлияли на настройки, может не выгрузились изменения на гитхаб?
я брал последнюю версию 4 дня назад выгруженную

**Comment by Oxotka** [comment]
Перепроверил - все есть.
Вот см. скриншот
![Настройки](https://user-images.githubusercontent.com/5194393/103683691-913ab100-4f9b-11eb-8e8c-5b92a69d6d26.png)

**Comment by mors1eska** [comment]
только добрался
ОСВ по 91 счету нужно 2 доделки:

1. Назвать ОСВ по счету 91.01
2. Добавить группировку "прочий доход расход"
![image](https://user-images.githubusercontent.com/34914654/104848552-8d415400-58f6-11eb-9198-be79f58aeb55.png)

**Comment by mors1eska** [comment]
Остальное - ок!

**Comment by Oxotka** [comment]
Отработал замечания. Просьба проверить
