### ISSUE TITLE
В случае изменения налоговой неверно ищутся данные декларации по Прибыли

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#23]
Если у ораганизации есть обособленные подразделения, то она сдает много деклараций по прибыли

![image](https://user-images.githubusercontent.com/34914654/100987092-1bd45e80-355f-11eb-84fa-9e0c8c26968b.png)

Но нам нужна только одна из них

У нас был код, который ищет декларацию по коду налоговой инспекции, а ниже - более точный код про головную

![image](https://user-images.githubusercontent.com/34914654/100987191-3eff0e00-355f-11eb-8bad-227ecc1817d2.png)

я сейчас закомментил 1ю проверку, т.к. ее надо делать либо периодической (искать когда какой код был), либо не проверять вовсе этот показатель

пока не знаю как правильно

**Comment by Oxotka** [comment]
Если это работает, то можно и оставить. Кажется, что это очень разовая операция и ради нее что-то делать не стоит.

**Comment by mors1eska** [comment]
ок
