### ISSUE TITLE
Обновить демо-версию декларации

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#24]
- надо проверить работоспособность на последней версии
- научить работать с обновленной декларацией по прибыли
- вставить доработки по сверке прибыли и ОСВ

по сути это все из рабочей надо взять

почему это надо?
50% тех кто к нам обращается за демо версией не хотят брать рабочую, т.к. демо не работает (негативно реагируют на то, что надо смотреть только прошлые года)

**Comment by Oxotka** [comment]
Сделал вот это:
- надо проверить работоспособность на последней версии
- научить работать с обновленной декларацией по прибыли

Не понял, что нужно сделать для:
- вставить доработки по сверке прибыли и ОСВ

Покажи, пожалуйста, на примере.

**Comment by mors1eska** [comment]
_вставить доработки по сверке прибыли и ОСВ
Покажи, пожалуйста, на примере._

Это я имею в виду вот этот функционал
![image](https://user-images.githubusercontent.com/34914654/104848638-0e98e680-58f7-11eb-97d0-b4cdb7b25b0c.png)

**Comment by Oxotka** [comment]
Так он же есть:
![Demo](https://user-images.githubusercontent.com/5194393/105672117-edd32100-5ef4-11eb-8d95-9ec221d48498.png)
