### ISSUE TITLE
Адаптация раздлелов с декларациями (без разниц)

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#26]
Пока не анализируем постоянные и временные разницы, только то что в декларациях и бухучете

**Comment by mors1eska** [comment]
![image](https://user-images.githubusercontent.com/34914654/105625434-6d4fea00-5e3a-11eb-9165-0bcbed551d38.png)

**Comment by Oxotka** [comment]
Здесь что-то нужно делать? Что?
