### ISSUE TITLE
Поддержка новой формы декларации по Прибыли 4-квартал 2020

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#29]

**Comment by mors1eska** [comment]
1. у нас по иначе берется код для старых отчетов, а нужный код - только для нужных форм, может как-то переделать, что бы иначе бралось как для новых форм - "многоуровневые разделы", тогда будет больше шансов, что код сам собой заработает (может есть еще более верные идеи для оптимизации?
![image](https://user-images.githubusercontent.com/34914654/105945100-a7f19680-6075-11eb-8a78-6a54b4533b06.png)

**Comment by mors1eska** [comment]
я добавил вот так и заработало
![Uploading image.png…]()

но лучше как-то нормально сделать

**Comment by mors1eska** [comment]
и в демо-версии надо будет такое поправить тоже
а то скачивают и сразу ошибку получают сейчас

**Comment by Oxotka** [comment]
Добавил вывод сообщения, что расширение не актуализировано и подключил формы 2020
