### ISSUE TITLE
Неверно определяются состояния отчетов (сдан не сдан)

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#34]
Появился регистр сведений для этого

`РегистрыСведений.ЖурналОтчетовСтатусы`

**Comment by mors1eska** [comment]
![image](https://user-images.githubusercontent.com/34914654/123527123-90cad980-d6e5-11eb-8082-7a31eb4afc1a.png)

Надо переделать выборку на запрос и сразу присоединить статусы из регистра

**Comment by Oxotka** [comment]
Исправлено
