### ISSUE TITLE
Не проходит аудит на ФРЕШ

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#35]
Я пишу как могу, надо поправить

Расширение конфигурации БП:Анализ расхождений выручки НДС и Налога на прибыль (версия 1.22 от 28.09.2021 8:50:30 UTC):
1. Расширение не должно приводить к чрезмерной нагрузке на компоненты сервиса или клиентское приложение.
Если в запросе используется получение значения через точку от поля составного ссылочного типа, то при выполнении этого запроса будет выполняться соединение со всеми таблицами объектов, входящими в этот составной тип. В результате SQL текст запроса чрезвычайно усложняется, и при его выполнении оптимизатор СУБД может выбрать неоптимальный план. Это может привести к серьезным проблемам производительности и даже к неработоспособности запроса в отдельных случаях.
В частности, не рекомендуется обращаться к реквизитам регистратора регистра (например, "НДСПредъявленныйОбороты.Регистратор.Сделка") и т. п. При этом не важно, в какой части запроса вы используете реквизит, полученный через точку от поля составного типа, - в списке возвращаемых полей, в условии и т. п. Во всех случаях такое обращение может привести к проблемам производительности.
Подробнее с причинами неоптимальной работы запросов и их оптимизацией можно ознакомиться здесь https://its.1c.ru/db/v8std#browse:13:-1:26:28

**Comment by Oxotka** [comment]
Просьба проверить

**Comment by mors1eska** [comment]
все прошло
