### ISSUE TITLE
Выложить в гитхаб, провести кодревью

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#36]
я много проверок добавил, надо проверить

[ПР_АнализРасхожденийВыручкиНДСИНалогаНаПрибыль 1.22.cfe.zip](https://github.com/Oxotka/VerificationOfRegulatoryReports/files/7243421/_.1.22.cfe.zip)

**Comment by Oxotka** [comment]
Готово.
Ошибки буду исправлять в рамках совместимо и аудита фреза
