### ISSUE TITLE
Улучшить открытие ОСВ по 91 счету из Настроек

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#37]
Нужно открывать отчет с настройками

![image](https://user-images.githubusercontent.com/34914654/135080870-7d336ba0-78d2-4a15-b709-18a2082da3e3.png)

**Comment by Oxotka** [comment]
Просьба проверить.

**Comment by mors1eska** [comment]
тут все ок
