### ISSUE TITLE
Сертификация 1С:Совместимо

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#39]
https://1c.ru/rus/products/1c/predpr/compat/compsert.htm
https://infostart.ru/1c/articles/801229/
https://1c.ru/rus/products/1c/predpr/compat/softreq.htm

Жолудева Марина - ответственное лицо
89646371473

**Comment by mors1eska** [comment]
![image](https://user-images.githubusercontent.com/34914654/137706359-3b5af281-59fe-4c5d-915f-36c389b9f6ee.png)

![image](https://user-images.githubusercontent.com/34914654/137706391-341b287f-6725-47ea-8e32-164909eddedc.png)

![image](https://user-images.githubusercontent.com/34914654/137706406-7efab04c-eaa5-4da8-9645-74c83d39eb2b.png)

![image](https://user-images.githubusercontent.com/34914654/137706427-d1dc562a-4241-48a6-a686-75f791221d04.png)

**Comment by Oxotka** [comment]
Заложился. Просьба проверить.

**Comment by mors1eska** [comment]
Ура ура
https://1c.ru/news/info.jsp?id=28829
