### ISSUE TITLE
Перестали анализироваться возвраты из документов Отчет о розничных продажах

### ISSUE THREAD

**Issue by mors1eska** [Oxotka/VerificationOfRegulatoryReports#40]
ДополнитьПоказателиУчетнымиДаннымиВозвратОтПокупателя

мы походу запрос оптимизировали тут и поломали про Отчет о розничных продажах
как тут правильно попоравить?
в таблице возвратов же нет Отчета
может надо в отдельную проверку даже выделить отчеты о рознице

`ВЫБРАТЬ
		ВозвратТоваровОтПокупателя.Сделка КАК Сделка,
		ВозвратТоваровОтПокупателя.Ссылка КАК ВозвратДокумент
	ПОМЕСТИТЬ ВТ_Возвраты
	ИЗ
		Документ.ВозвратТоваровОтПокупателя КАК ВозвратТоваровОтПокупателя
	ГДЕ
		ВозвратТоваровОтПокупателя.Организация = &Организация
		И ВозвратТоваровОтПокупателя.Дата МЕЖДУ &НачалоПериода И &КонецПериода
		И ВозвратТоваровОтПокупателя.Проведен
	;
	
	////////////////////////////////////////////////////////////////////////////////
	ВЫБРАТЬ
		РеализацияТоваровУслуг.Дата КАК ДатаОснования,
		ВТ_Возвраты.ВозвратДокумент КАК ВозвратДокумент
	ПОМЕСТИТЬ ВТ_ДатыОснования
	ИЗ
		ВТ_Возвраты КАК ВТ_Возвраты
			ЛЕВОЕ СОЕДИНЕНИЕ Документ.РеализацияТоваровУслуг КАК РеализацияТоваровУслуг
			ПО ВТ_Возвраты.Сделка = РеализацияТоваровУслуг.Ссылка
	ГДЕ
		ГОД(РеализацияТоваровУслуг.Дата) = ГОД(&НачалоПериода)
	
	ОБЪЕДИНИТЬ ВСЕ
	
	ВЫБРАТЬ
		ОтчетОРозничныхПродажах.Дата,
		ВТ_Возвраты.ВозвратДокумент
	ИЗ
		ВТ_Возвраты КАК ВТ_Возвраты
			ЛЕВОЕ СОЕДИНЕНИЕ Документ.ОтчетОРозничныхПродажах КАК ОтчетОРозничныхПродажах
			ПО ВТ_Возвраты.Сделка = ОтчетОРозничныхПродажах.Ссылка
	ГДЕ
		ГОД(ОтчетОРозничныхПродажах.Дата) = ГОД(&НачалоПериода)
	;
	
	////////////////////////////////////////////////////////////////////////////////
	ВЫБРАТЬ
		-НДСПредъявленныйОбороты.СуммаБезНДСПриход КАК Сумма,
		НДСПредъявленныйОбороты.Регистратор КАК Документ,
		НДСПредъявленныйОбороты.Поставщик КАК Информация
	ИЗ
		РегистрНакопления.НДСПредъявленный.Обороты(
				&НачалоПериода,
				&КонецПериодаГраница,
				Регистратор,
				Организация = &Организация
					И СтавкаНДС <> &СтавкаБезНДС
					И ВидЦенности = ЗНАЧЕНИЕ(Перечисление.ВидыЦенностей.Возврат)) КАК НДСПредъявленныйОбороты
			ЛЕВОЕ СОЕДИНЕНИЕ ВТ_ДатыОснования КАК ВТ_ДатыОснования
			ПО НДСПредъявленныйОбороты.Регистратор = ВТ_ДатыОснования.ВозвратДокумент
	ГДЕ
		ЕСТЬNULL(ВТ_ДатыОснования.ДатаОснования, &ПустаяДата) <> &ПустаяДата

вот весь запрос`

**Comment by Oxotka** [comment]
А какая логика должна быть? Просто все отчеты должны попадать или что?

**Comment by mors1eska** [comment]
Не исправилось
Оказалось, что бывают вот такие варианты

![image](https://user-images.githubusercontent.com/34914654/140922095-24c6a469-a062-472e-8501-0b2b9ae00ed0.png)
